#!/bin/bash
#
# program
#

__dirname="$(cd "$(dirname "$BASH_SOURCE")"/.. && pwd)"

. "$__dirname"/bin/argue.sh

argv=("$@")
argue "-v, --version"\
      "-f, --first-name, +"\
      "-l, --last-name, +"

echo "options (${#opts[@]}): ${opts[@]}"
echo "arguments (${#args[@]}): ${args[@]}"
